version: '3.8'
services:
  coolcert:
    build: .
    restart: always
    ports:
    - "3002:3002"
    environment:
      HOSTING_DOMAIN: 'http://localhost:3002'
      PORT: 3002
      SERVER_PRIVATE_KEY: '' # TODO (developer): Use your own key
      NODE_ENV: development
      DOJO_URL: 'https://staging-dojo.babbage.systems'
